model_type: deepspeech
model: data/deepspeech/
model_save_dir: data/pretrained_models/
model_path: data/pretrained_models/deepspeech/librispeech_pretrained_v3.ckpt
audio_files_path: data/dataset_timit/data/TEST/DR1