model_type: deepspeech
model: data/deepspeech/
model_save_dir: data/pretrained_models/
model_path: data/pretrained_models/deepspeech/deepspeech-0.9.3-models.pbmm
model_score_path: data/pretrained_models/deepspeech/deepspeech-0.9.3-models.scorer
audio_path: adv_result.wav