model_type: speechbrain
model: speechbrain/asr-crdnn-rnnlm-librispeech
model_save_dir: data/pretrained_models/
# audio_path: speechbrain/asr-crdnn-rnnlm-librispeech/example.wav
audio_path: test/SI472.WAV.wav_new.wav